version: '3.8'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    container_name: backend
    env_file: ./.env
    ports:
    - "3000:3000"
    command: npm run server
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - .:/app
       - ./backend:/usr/src/app
    depends_on:
      - mongodb
    networks:
      -  mern-blog
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/react/Dockerfile
    container_name: frontend
    ports:
    -  "7200:80"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    networks:
      - mern-blog

  

  mongodb:
    image: mongo:4.0 
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27018"
    volumes:
      - ./mydata:/data/db
    networks:
      - mern-blog
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - mern-blog


networks:
    mern-blog:
        driver: bridge


volumes: 
  mydata:
  static_volume: 